name: recipes_dev
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: recipes
    ports:
      - 5432:5432
    # volumes:
    #   - ${PROJECT_PATH}:/var/lib/postgresql/data
    restart: always

  api_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    image: recipes-backend:v0
    container_name: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    restart: always

  # frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile.dev
  #     no_cache: true
  #   image: recipes-front:v0
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #     - 3010:3010
  #   depends_on:
  #     - api_backend
  #   restart: always
  #   volumes:
  #     - ./front:/usr/src/front
  #     - /usr/src/front/node_modules

# volumes:
#   ${PROJECT_PATH}:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./backend/db

