version: '3.8'

name: recipes
services:
  front:
    container_name: frontend
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 80:80
  # backend:
  #   container_name: backend
  #   restart: always
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #     no_cache: true
  #   ports:
  #     - 8080:8080
