name: recipes_dev
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container_dev
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: recipes
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    restart: always

  frontend:
    container_name: frontend_dev
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      no_cache: true
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - 3000:3000
      - 3010:3010
    depends_on:
      - backend
    restart: always
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
      - ./resources/recipes:/var/resources/recipes

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres-docker-data
  recipes_vm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources/recipes
