version: '3.8'

name: recipes
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: recipes
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend
    image: inith/recipe-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    restart: always

  frontend:
    container_name: frontend
    image: inith/recipe-app-frontend
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      AUTH_AUTH0_ID: ${AUTH_AUTH0_ID}
      AUTH_AUTH0_SECRET: ${AUTH_AUTH0_SECRET}
      ORIGIN: ${ORIGIN}
      AUTH_SECRET: ${AUTH_SECRET}
    volumes:
      - ./front/build:/var/resources/recipes/build
      - ./resources/recipes:/var/resources/recipes
      - ./resources/images:/var/resources/images

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres-docker-data
  recipes_vm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources
