package app.recipe.backend.model;

public enum Category{
	CAKES_AND_PIES,
	COOKIES,
	DESSERTS,
	CUPCAKES_AND_MUFFINS,
	DONUTS_AND_BAGELS,
	CHEESECAKES,
	PANCAKES_AND_FLAPJACKS,
	BREADS_AND_ROLLS,
	MEAT_DISHES,
	MEATLESS_DISHES,
	FISH_DISHES,
	SWEET_DISHES,
	SOUPS,
	SALADS_AND_SLAWS,
	SAUCES_AND_PASTES,
	SNACKS,
	PRESERVES,
	DRINKS_AND_COCKTAILS,
	SPIRITS_AND_LIQUEURS,
	HOMEMADE_ICE_CREAM
}
